experiment_name: "vit_finetune_from_smae"

model:
  architecture: "ViT_1D"
  input_length: 500
  patch_size: 20
  embedding_dim: 256
  dim_mlp: 512        # <--- AGGIUNGI QUESTA RIGA!
  depth: 8
  heads: 8
  n_classes: 2
  dropout: 0.3

pretrain:
  # Percorso ai pesi generati dall'esperimento Spectra_MAE
  pretrained_path: "experiments/pretraining/exp_02_smae/best_pretrained_model.pth"

training:
  mode: "finetune"        # Esegue prima Linear Probing, poi Fine-Tuning totale
         # Epoche in cui si allena TUTTA la rete
  lr_lp: 1e-3             # Learning rate alto per la testa (parte da zero)
  lr_ft: 1e-5             # Learning rate basso per non "dimenticare" il pre-training

  patience: 15
  batch_size: 32
  
  # ATTENZIONE QUI: Questo è il nome dell'ultimo layer nel file ViT_1D.py!
  # Di solito nei ViT si chiama "mlp_head", "head" o "classifier". 
  head_attr: "classifier"       

dataset:
  path: "data/IBD/Processed/IBD_Dataset_500pt.mat" # Modifica se il path è diverso
  x_key: "X"
  y_key: "y"

split:
  type: "kfold"
  n_splits: 5
  seed: 42